name = "initiative-feedback"
type = "rust"
account_id = "186bcc49898ec25db1f9a2d907554c60"
workers_dev = true

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "24265fb0801c4bfa867ce400bc7c170d"
preview_id = "24265fb0801c4bfa867ce400bc7c170d"

[env.staging]
kv_namespaces = [ { binding = "RATE_LIMIT", id = "dedca7225d724b43b863e5b6712a7926" } ]
route = "https://staging.initiative.sh/feedback"
workers_dev = false
zone_id = "d9062a48db53cc686deedf69442e9973"

[env.production]
kv_namespaces = [ { binding = "RATE_LIMIT", id = "dedca7225d724b43b863e5b6712a7926" } ]
route = "https://initiative.sh/feedback"
workers_dev = false
zone_id = "d9062a48db53cc686deedf69442e9973"
