[package]
name = "initiative-macros"
version = "0.1.0"
authors = ["Mikkel Paulson <git@email.mikkel.ca>"]
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
initiative-reference = { path = "../reference" }
quote = "1.0"
syn = "1.0"
