name: Changelog

on:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-for-updates:
    name: Has been updated in this branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check file diff
        run: git diff --name-only origin/main | grep -xq data/changelog.md
