name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    name: Unit tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run rustfmt
        run: find */src -name '*.rs' -exec rustfmt --check --verbose '{}' +
      - name: Run Clippy
        run: cargo clippy -- --deny warnings
      - name: Run unit tests
        run: cargo test --workspace --verbose
