name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  code-standards:
    name: Code standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run rustfmt
        run: git ls-files '*.rs' | xargs rustfmt --check --edition 2018 --verbose
      - name: Run Clippy
        run: cargo clippy --workspace -- --deny warnings

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run unit tests
        run: cargo test --workspace --verbose

  browser-wasm-tests:
    name: Browser WASM tests (Firefox and Chrome)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install wasm-pack
        run: npm install -g wasm-pack
      - name: Run Firefox WASM tests
        run: wasm-pack test --firefox --headless
        working-directory: web
      - name: Run Chrome WASM tests
        run: wasm-pack test --chrome --headless
        working-directory: web
